---
title: "Analysis of Dominique's  RNAseq Data "
output: 
  html_notebook:
    number_sections: yes
    toc: yes
    toc_float: yes
    theme: united
    highlight: tango
    code_folding: hide
author: "Frank"
date: "`r date()`"
---
# Libraries 

```{r}
require(dplyr)
require(limma)
require(ggplot2)
require(edgeR)

require(org.Mm.eg.db)
require(biomaRt)
getGsymble <- function(glist){

  try(symbol <- mapIds(org.Mm.eg.db,
                   keys=glist,
                   column="SYMBOL",
                   keytype="ENSEMBL",
                   multiVals="first"))
  
  ensembl = useEnsembl(biomart="ensembl",dataset = "mmusculus_gene_ensembl")
  if(!exists('symbol'))
    symbol <- getBM(attributes=c('ensembl_gene_id','mgi_symbol'),filters = 'ensembl_gene_id',
                                   values  =glist, mart = ensembl)$mgi_symbol
  
  if( sum(is.na(symbol))>0)
    symbol[is.na(symbol)] <- getBM(attributes=c('ensembl_gene_id','mgi_symbol'),filters = 'ensembl_gene_id',
                                   values  =glist[is.na(symbol)], mart = ensembl)$mgi_symbol
  
  if(sum(is.na(symbol))>0)
    symbol[(is.na(symbol))]<- names(symbol[(is.na(symbol))])
  
  symbol
  
}


```



# NES vs WT paired compares
```{r}
load(file='./2017-04-04-analysis1/edgeR_cmp.data')

# compare pairs 
edger.comp.mat <- data.frame(
  NESvWT_12_0= c(1,-1,0,0,0,0),
  NESvWT_12_12= c(0,0,1,-1,0,0),
  NESvWT_24_24=c(0,0,0,0,1,-1))

lrt <- sapply(colnames(edger.comp.mat),function(x)
  glmLRT(fit,contrast = edger.comp.mat[,x]),simplify = F)

glt  <- sapply(colnames(edger.comp.mat),function(x)
  glmTreat(fit,contrast = edger.comp.mat[,x],lfc = 1))

# threshold 
th.fdr <- .05; th.lfc <- .5
edger.NESvWT.DEGs <- lapply(lrt,function(x) decideTestsDGE(x,p.value = th.fdr,lfc = th.lfc))
glist.NESred <- unique(unlist(lapply(edger.NESvWT.DEGs,function(x) which(x==-1))))


```

## MAplot 
```{r}
par(mfrow=c(2,2))
for(i in 1:3){
  plotSmear(lrt[[i]],de.tags = rownames(y)[as.logical(edger.NESvWT.DEGs[[i]])],
            main=colnames(edger.comp.mat)[i])
  abline(h=c(-th.lfc, th.lfc), col="blue")
  text(10,3,paste0('Up:',summary(edger.NESvWT.DEGs[[i]])[3],'\n Down:',summary(edger.NESvWT.DEGs[[i]])[1]))
}
par(mfrow=c(1,1))

```
## Venn diagram 
```{r}
require(venn)
venn(lapply(edger.NESvWT.DEGs,function(x) which(x==-1)),zcolor = "style",cexil = 0.75)
# number of down-regulation genes
length(unique(unlist(lapply(edger.NESvWT.DEGs,function(x)which(x==1)))))

NESvWT.glist.l <- lapply(edger.NESvWT.DEGs,function(x)which(x==-1))
```
## who are they 
```{r}
require(VennDiagram)
g.cates <- calculate.overlap(lapply(edger.NESvWT.DEGs,
                                    function(x)which(x==-1)))
NESvWT.glist <- data.frame(
  ids = unlist(g.cates),
  cates = unlist(sapply(1:7,function(x) rep(x,length(g.cates[[x]]))))
)
NESvWT.glist<- NESvWT.glist %>% mutate(ensemble = y$genes$Geneid[ids])
NESvWT.glist<-NESvWT.glist%>% mutate(Symbol=getGsymble(ensemble))
write.csv(file='NESvWT_down_glist.csv',NESvWT.glist)


#cat((NESvWT.glist%>%filter(cates==1)%>%dplyr::select(Symbol))$Symbol)
```

## heatmap of rpkm 
```{r}
rpkm <- read.csv(file = './data/rpkm_expressed_gene.csv',
                 stringsAsFactors = F,row.names = 1)[,3:20]
rpkm <- rpkm[c(1,7,13,2,8,14,3,9,15,4,10,16,5,11,17,6,12,18)]
pd <- log2(rpkm[NESvWT.glist$ensemble,]+1)
pd <- rpkm[NESvWT.glist$ensemble,]
require(pheatmap)
pd <- t(scale(t(pd))); m <- max(abs(range(pd)))
pheatmap(pd,scale = "none",show_rownames = F,cluster_cols = F,
         colorRampPalette(c("navy", "white", "firebrick3"))(20),
         breaks = seq(-m,m,length.out = 21))

```
## barplot
```{r}
require(tidyr)
barfun <- function(id){
  
  if(class(id)=='character' & length(id)!=18) {
    id <- which(NESvWT.glist$Symbol==id)
  }else if(class(id)=='integer'){
    id<- which(NESvWT.glist$ids==id)}
  
  pd.1<- pd[id,]
  
  pd.1 <- data.frame(rpkm=as.numeric(pd.1),
                     sample_key = names(pd.1))
  pd.1<- pd.1 %>% separate(sample_key,into = c('geno','aCD3_aCD28','a4_1BB','rep'),sep = '_')  
  pd.1<- pd.1%>% unite(col='treat',3:4,sep = '_',remove=F)
  pd.2 <- pd.1 %>% group_by(treat,geno)%>% summarise(m=mean(rpkm),s= sd(rpkm)/sqrt(length(rpkm))) # SE
  pd.2$geno <- factor(pd.2$geno,levels = c('WT','NES'))
  ggplot(pd.2,aes(treat,m,fill=geno)) + geom_bar(position='dodge',stat = 'identity',colour='black')+ 
    geom_errorbar(position=position_dodge(.9),aes(ymax=m+s,ymin=m-s),width=.2)+
    ylab('RPKM')+ scale_fill_manual(values=c("black","#CCCCCC"))+theme_bw()+
    ggtitle(NESvWT.glist$Symbol[id]) + xlab("")
}

barfunMerge <- function(id){
  #id <- rownames(pd)[h$tree_row$order[1:13]]

  if(class(id)=='character' & length(id[1])!=18) {
        gs <- id
    id <- which(NESvWT.glist$Symbol%in% id)

  }else if(class(id)=='integer'){
    id<- which(NESvWT.glist$ids %in% id)}
  pd <- rpkm[NESvWT.glist$ensemble,]
  pd.2<- pd[id,]
  
  pd.1 <- data.frame(melt(pd.2,variable_name = 'sample_key'),
             gene = rep(NESvWT.glist$Symbol[id],ncol(pd.2)))
  pd.1 <- pd.1 %>% dplyr::rename(rpkm=value)
  pd.1<- pd.1 %>% separate(sample_key,into = c('geno','aCD3_aCD28','a4_1BB','rep'),sep = '_')  
  pd.1<- pd.1%>% unite(col='treat',2:3,sep = '_',remove=F)
  pd.2 <- pd.1 %>% group_by(treat,geno,gene)%>% summarise(m=mean(rpkm),s= sd(rpkm)/sqrt(length(rpkm))) # SE
  pd.2$geno <- factor(pd.2$geno,levels = c('WT','NES'))
  pd.2$gene <- factor(pd.2$gene,levels = gs)
  ggplot(pd.2,aes(treat,m,fill=geno)) + geom_bar(position='dodge',stat = 'identity',colour='black')+ 
    geom_errorbar(position=position_dodge(.9),aes(ymax=m+s,ymin=m-s),width=.2)+
    ylab('RPKM')+ scale_fill_manual(values=c("black","#CCCCCC"))+theme_bw()+
    xlab("") + facet_wrap(~gene,scales = 'free_y')
}

barfun('Serpina3g')
```



# WT induction 
```{r}
edger.comp.mat <- data.frame(WT12_12= c(0,-1,0,1,0,0),
                             WT24_24=c(0,-1,0,0,0,1))
lrt <- sapply(colnames(edger.comp.mat),function(x)
  glmLRT(fit,contrast = edger.comp.mat[,x]),simplify = F)

glt  <- sapply(colnames(edger.comp.mat),function(x)
  glmTreat(fit,contrast = edger.comp.mat[,x],lfc = 1))

# threshold 
edger.DEGs <- lapply(lrt,function(x) decideTestsDGE(x,p.value = th.fdr,lfc = 1))
glist.wtup <- (unique(unlist(lapply(edger.DEGs,function(x) which(x==1)))))
length(glist.wtup)
```



## how many NES reduced genes are induced in WT
```{r}
data.frame (NESred=length(glist.NESred),
  WTup = length(glist.wtup),
  NESred_WTup = sum(glist.NESred%in% glist.wtup))
```
```{r}
# of those genes in WT list how they distributed 
NESvWT.glist.l2 <- lapply(NESvWT.glist.l,function(x) x[x%in%glist.wtup])
venn(NESvWT.glist.l2,zcolor = "style",cexil = 0.75)

```

## plotting all of them 

```{r}
require(gridExtra)
tmp <- calculate.overlap(NESvWT.glist.l2)
p1<- lapply(tmp$a1,barfun)
grid.arrange(p1[[1]],p1[[2]],p1[[3]],p1[[4]],p1[[5]],ncol=3)
```

# Session Info 
```{r}
sessionInfo() 
```


